$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
display_name: scenera-production-job
code: model
command: >-
  python train.py
  --training_data ${{inputs.training_data}}
  --reg_rate ${{inputs.reg_rate}}
inputs:
  training_data: 
    type: uri_folder 
    path: azureml://datastores/workspaceblobstore/paths/LocalUpload/386681db2f7cd59e8c96f5ee80b212db/data/
  reg_rate: 0.01
environment: azureml:AzureML-sklearn-0.24-ubuntu18.04-py37-cpu@latest
compute: azureml:scenera-mlops-cluster-4
experiment_name: Scenera
description: Scenera Demo