name: Trigger Azure Machine Learning pipeline

on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  train-dev:
    runs-on: ubuntu-latest
    environment: development
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: run training job
      #run: az ml job create --file job.yml --resource-group scenera-demo --workspace-name aml-scenera-demo-2 --stream
      run: az ml job list --resource-group scenera-demo --workspace-name aml-scenera-demo-2
      working-directory: src/
  train-prod:
    needs: train-dev
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y    
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}  
    - name: run prod job
      run: az ml job create --file prod-job.yml --resource-group scenera-demo --workspace-name aml-scenera-demo-2 --stream
      working-directory: src/      
  register-model:
    runs-on: ubuntu-latest
    needs: train-prod
    steps:
    - name: Registering Model
      run: echo "Registering the model...."
